services:
  mongo:
    container_name: mongo
    image: mongo:4.4.24
    ports:
      - 27017:27017
    networks:
      custom_network:
        ipv4_address: 192.168.1.10

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions \"/etc/rabbitmq/definitions.json\""
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/config.json:/etc/rabbitmq/definitions.json
    networks:
      custom_network:
        ipv4_address: 192.168.1.11

  redis-master:
    container_name: "redis-master"
    image: redis:6.0-alpine
    command: redis-server --requirepass password1 --masterauth password1
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password1
    networks:
      custom_network:
        ipv4_address: 192.168.1.20

  redis-slave1:
    container_name: "redis-slave1"
    image: redis:6.0-alpine
    ports:
      - "6380:6379"
    command: redis-server --slaveof 192.168.1.20 6379 --masterauth password1 --requirepass password1
    depends_on:
      - redis-master
    networks:
      custom_network:
        ipv4_address: 192.168.1.21

  redis-slave2:
    container_name: "redis-slave2"
    image: redis:6.0-alpine
    ports:
      - "6381:6379"
    command: redis-server --slaveof 192.168.1.20 6379 --masterauth password1 --requirepass password1
    depends_on:
      - redis-master
    networks:
      custom_network:
        ipv4_address: 192.168.1.22

  redis-sentinel1:
    container_name: 'redis-sentinel1'
    image: redis:6.0-alpine
    ports:
      - "26379:5000"
    command: sh -c "mkdir -p /etc/sentinel && cp /defaults/sentinel.conf /etc/sentinel/sentinel.conf && redis-server /etc/sentinel/sentinel.conf --sentinel"
    volumes:
      - "./sentinel/sentinel.conf:/defaults/sentinel.conf"
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    networks:
      custom_network:
        ipv4_address: 192.168.1.30
    environment:
      - SENTINEL_PASSWORD=password2

  redis-sentinel2:
    container_name: 'redis-sentinel2'
    image: redis:6.0-alpine
    ports:
      - "26380:5000"
    command: sh -c "mkdir -p /etc/sentinel && cp /defaults/sentinel.conf /etc/sentinel/sentinel.conf && redis-server /etc/sentinel/sentinel.conf --sentinel"
    volumes:
      - "./sentinel/sentinel.conf:/defaults/sentinel.conf"
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    networks:
      custom_network:
        ipv4_address: 192.168.1.31
    environment:
      - SENTINEL_PASSWORD=password2

  redis-sentinel3:
    container_name: 'redis-sentinel3'
    image: redis:6.0-alpine
    ports:
      - "26381:5000"
    command: sh -c "mkdir -p /etc/sentinel && cp /defaults/sentinel.conf /etc/sentinel/sentinel.conf && redis-server /etc/sentinel/sentinel.conf --sentinel"
    volumes:
      - "./sentinel/sentinel.conf:/defaults/sentinel.conf"
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    networks:
      custom_network:
        ipv4_address: 192.168.1.32
    environment:
      - SENTINEL_PASSWORD=password2

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
